---
title: "DMPA_Assignment6"
output: word_document
date: "2024-11-21"
---

```{r}
library(dplyr)
library(RColorBrewer)
library(arules)
```


```{r}
df <- read.csv("C:/Users/conma/Downloads/movie-dataset/vodclickstream_uk_movies_03.csv", header=TRUE)
head(df)
df5 <- df %>%
  select(user_id, title)
head(df5)
str(df)
```

```{r}
df2 <- df %>%
  select(user_id, title) %>%
  arrange(user_id)
head(df2)

# This only selects user ID and movie title  and arranges by user ID in ascending order
```

```{r}
df2 <- df2 %>% 
  distinct()
head(df2)

# This gets rid of all duplicate rows in the dataset.
```


```{r}
trans1 <- transactions(df2, format = "long", cols = c("user_id", "title"))
#inspect(trans2)
```

```{r}
arules::itemFrequencyPlot(trans1, topN = 10,
                          col = brewer.pal(8, 'Pastel2'),
                          main = 'Relative Item Frequency Plot',
                          type = "relative",
                          ylab = "Item Frequency (Relative)",
                          cex.names = .6)
```

```{r}
rules <- apriori(trans1, parameter = list(supp = 0.00008, conf = 0.02, minlen=2))

# top 10 rules by lift
lift_rules <- sort(rules, by = "lift", decreasing = TRUE)
print(as(head(lift_rules, 10), "data.frame"))
```

```{r}
fury_rules <- apriori(trans1, parameter = list(supp = 0.00008, conf = 0.02, minlen = 2), appearance = list(default = "rhs", lhs="Fury"))
fury_rules1 <- sort(fury_rules, by = "lift", decreasing = TRUE)
print(as(head(fury_rules1, 10), "data.frame"))
```


```{r}
top_10_rules <- head(lift_rules, 10)
plot(top_10_rules, method = "graph",  engine = "htmlwidget")
```


```{r}
# top 10 rules by confidence
conf_rules <- sort(rules, by = "confidence", decreasing = TRUE)
print(as(head(conf_rules, 10), "data.frame"))
```

```{r}
# top 10 rules by support
supp_rules <- sort(rules, by = "support", decreasing = TRUE)
print(as(head(supp_rules, 10), "data.frame"))
```

```{r}
plot(rules, method="two-key plot")
```



```{r}
 plot(rules, measure = c("support", "lift"), shading = "confidence")
```



```{r}
get_recommendations <- function(movie, rules, top_n = 5) {
  
  # Define a set of stop words
  stopwords <- c("the", "to", "and", "of", "in", "a", "an", "is", "on", "at", "with")
  
  # Split the input movie title into individual words
  movie_parts <- unlist(strsplit(movie, "\\s+"))
  
  # Remove stopwords from movie_parts
  movie_parts <- movie_parts[!movie_parts %in% stopwords]
  
  # Filter rules where the given movie is in the LHS (antecedent)
  movie_rules <- subset(rules, lhs %in% movie)
  
  # Sort rules by lift
  sorted_rules <- sort(movie_rules, by = "lift", decreasing = TRUE)
  
  # Extract recommendations from rhs
  recommendations <- unique(unlist(as(rhs(sorted_rules), "list")))
  
  # Filter out recommendations containing any part of the input movie title excluding the stopwords above
  recommendations <- recommendations[!sapply(recommendations, function(rec) {
    any(sapply(movie_parts, function(part) grepl(part, rec, ignore.case = TRUE)))
  })]
  
  # Return the top N recommendations
  return(head(recommendations, top_n))
}
```


```{r}

# Prompt the user to input a movie title
movie_title <- readline(prompt = "Enter a movie title: ")

# Get recommendations
recommendations <- get_recommendations(movie_title, rules, top_n = 5)

# Display recommendations 
if (length(recommendations) == 0 || grepl("No recommendations", recommendations[1])) {
  cat("\nNo recommendations found for:", movie_title, "\n")
} else {
  cat("\nRecommendations for '", movie_title, "':\n", sep = "")
  cat(recommendations, sep = "\n")
  cat("\n")
}
```


